# Generated by Django 4.1.2 on 2022-11-17 00:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tag', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'IdeaCategory',
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('date_added', models.DateField()),
                ('idea_category', models.ManyToManyField(to='Ideas.ideacategory')),
            ],
            options={
                'db_table': 'Idea',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=13)),
                ('date_joined', models.DateField(blank=True, default=datetime.datetime.today)),
                ('idea', models.ManyToManyField(blank=True, to='Ideas.idea')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
