# Generated by Django 4.1.2 on 2022-11-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ideas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='idea_category',
            new_name='category',
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='admin', max_length=30),
            preserve_default=False,
        ),
    ]
