# Generated by Django 4.1.2 on 2022-11-16 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ideas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='category',
            new_name='idea_category',
        ),
    ]
