# Generated by Django 4.1.2 on 2022-12-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ideas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideacategory',
            name='id',
        ),
        migrations.AlterField(
            model_name='ideacategory',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
