# Generated by Django 4.1.2 on 2022-11-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ideas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideacategory',
            name='tag',
        ),
    ]
