# Generated by Django 4.1.2 on 2022-12-12 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ideas', '0002_remove_ideacategory_tag'),
        ('Ideas', '0002_rename_category_idea_idea_category'),
        ('Ideas', '0002_rename_idea_category_idea_category_and_more'),
    ]

    operations = [
    ]
