# Generated by Django 4.1.2 on 2022-12-12 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ideas', '0003_merge_20221212_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='idea_category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='idea',
            name='date_added',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
