# Generated by Django 4.1.2 on 2022-12-12 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ideas', '0004_rename_idea_category_idea_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='idea',
        ),
        migrations.AddField(
            model_name='customer',
            name='idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ideas.idea'),
        ),
    ]
