# Generated by Django 4.1.2 on 2022-12-12 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ideas', '0006_remove_customer_email_remove_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='id',
        ),
        migrations.AddField(
            model_name='idea',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ideas.customer'),
        ),
        migrations.AddField(
            model_name='idea',
            name='idea_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
